export const ADD_TEMPAT = 'ADD_TEMPAT';
export const DELETE_TEMPAT = 'DELETE_TEMPAT';
export const DELETE_ALL_TEMPAT = 'DELETE_ALL_TEMPAT';
export const PILIH_TEMPAT = 'PILIH_TEMPAT';
export const UNPILIH_TEMPAT = 'UNPILIH_TEMPAT';
